### ISSUE TITLE
Not working on custom images

### ISSUE THREAD

**Issue by ayush9198gupta** [IssamLaradji/CBStyling#4]
Hi @IssamLaradji ,

I am running your model but when I am testing on custom images(on male/female) it is not  work although it is working on pre-trained image that you have uploaded in model.

I have also tested with the different style and class id but it is not working for male/female images.

Is their any issue with the loaded checkpoints , if yes kindly suggest or provide link for checkpoints for other images.

Thanks in advance

**Comment by IssamLaradji** [comment]
Hi @ayush9198gupta  sorry for the late reply, can you attach the custom images? I can test it and see where it is going wrong. Thanks

**Comment by uhnjiny** [comment]
Hi @IssamLaradji ,

I am a student studying computer science and I am trying to run your model. I have some questions.

What's the match between the class and the number in your code? (ex class 13 : car)

I tried to change the style by changing the number after s , but I got the error below.
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    main(args.img_fname, args.out_fname, args.style, args.class_id)
  File "main.py", line 8, in main
    style_model = ut.create_style_model(style_id)
  File "/mnt/KJA/CBStyling/utils.py", line 88, in create_style_model
    model_file = glob.glob('styles/*.pth')[style_number]
IndexError: list index out of range

Also, I want to run this code with video like you did. how can I do this?

Thanks in advance:)
